[browser]
gatherUsageStats = false

[server]
headless = true

[theme]
base = "light"
primaryColor = "#b11f4b"
backgroundColor = "#f7f4ef"
secondaryBackgroundColor = "#fcfbf8"
textColor = "#242424"
font = "sans serif"
